services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "1111:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "2222:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3333:3000"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "4444:3100"
    command: -config.file=/etc/loki/local-config.yaml

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluentbit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitorizacion_tfg  
      MYSQL_USER: user
      MYSQL_PASSWORD: clave
    ports:
      - "5555:3306"

  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    ports:
      - "6666:9104"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf:ro
    command:
      - "--config.my-cnf=/etc/mysql/my.cnf"

  jeremy_drupal1:
    image: drupal:10-apache
    container_name: jeremy_drupal1
    ports:
      - "7777:80"
    depends_on:
      - mysql
    volumes:
      - drupal_data:/opt/drupal/web

  jeremy_drupal2:
    image: drupal:10-apache
    container_name: jeremy_drupal2
    ports:
      - "8888:80"
    depends_on:
      - mysql
    volumes:
      - drupal_data:/opt/drupal/web

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "9999:80"
      - "9998:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - jeremy_drupal1
      - jeremy_drupal2

volumes:
  drupal_data: