[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Tag               docker.*

[OUTPUT]
    Name              loki
    Match             *
    Host              loki
    Port              3100


    